//
//  _CDContextualKeyPath+CDContextKeyPathBridge.swift
//  CoreDuetTinker
//
//  Created by Eric Rabil on 6/29/21.
//

import Foundation
import CoreDuetContext

extension _CDContextualKeyPath {
    var keyPath: CDContextKeyPath {
        switch self {
        case _CDContextQueries.keyPathForDefaultPairedDeviceCellQuality():
            return .defaultPairedDeviceCellQuality
        case _CDContextQueries.keyPathForDefaultPairedDeviceWiFiWiredQuality():
            return .defaultPairedDeviceWiFiWiredQuality
        case _CDContextQueries.keyPathForActiveComplications():
            return .activeComplications
        case _CDContextQueries.keyPathForDefaultPairedDeviceForegroundApp():
            return .defaultPairedDeviceForegroundApp
        case _CDContextQueries.keyPathForWatchForegroundApp():
            return .watchForegroundApp
        case _CDContextQueries.keyPathForDefaultPairedDeviceThermalPressureLevel():
            return .defaultPairedDeviceThermalPressureLevel
        case _CDContextQueries.keyPathForWatchThermalPressureLevel():
            return .watchThermalPressureLevel
        case _CDContextQueries.keyPathForDefaultPairedDevicePluginStatus():
            return .defaultPairedDevicePluginStatus
        case _CDContextQueries.keyPathForWatchPluginStatus():
            return .watchPluginStatus
        case _CDContextQueries.keyPathForDefaultPairedDeviceBatteryLevel():
            return .defaultPairedDeviceBatteryLevel
        case _CDContextQueries.keyPathForWatchBatteryLevel():
            return .watchBatteryLevel
        case _CDContextQueries.keyPathForWatchActiveStatus():
            return .watchActiveStatus
        case _CDContextQueries.keyPathForDefaultPairedDeviceNearbyStatus():
            return .defaultPairedDeviceNearbyStatus
        case _CDContextQueries.keyPathForWatchNearbyStatus():
            return .watchNearbyStatus
        case _CDContextQueries.keyPathForNetworkingBudgetRemainingStatus():
            return .networkingBudgetRemainingStatus
        case _CDContextQueries.keyPathForEnergyBudgetRemainingStatus():
            return .energyBudgetRemainingStatus
        case _CDContextQueries.keyPathForNearbyLOIIdentifiers():
            return .nearbyLOIIdentifiers
        case _CDContextQueries.keyPathForCPUUsageLevel():
            return .cPUUsageLevel
        case _CDContextQueries.keyPathForThermalPressureLevel():
            return .thermalPressureLevel
        case _CDContextQueries.keyPathForPluginStatus():
            return .pluginStatus
        case _CDContextQueries.keyPathForBatteryLevel():
            return .batteryLevel
        case _CDContextQueries.keyPathForLowBattery():
            return .lowBattery
        case _CDContextQueries.keyPathForSystemTime():
            return .systemTime
        case _CDContextQueries.keyPathForMotionState():
            return .motionState
        case _CDContextQueries.keyPathForWorkoutStatus():
            return .workoutStatus
        case _CDContextQueries.keyPathForCarplayConnectedStatus():
            return .carplayConnectedStatus
        case _CDContextQueries.keyPathForCellConnectionQuality():
            return .cellConnectionQuality
        case _CDContextQueries.keyPathForWiFiConnectionQuality():
            return .wiFiConnectionQuality
        case _CDContextQueries.keyPathForWiredConnectionQuality():
            return .wiredConnectionQuality
        case _CDContextQueries.keyPathForWiFiConnectionSSID():
            return .wiFiConnectionSSID
        case _CDContextQueries.keyPathForAirplaneModeStatus():
            return .airplaneModeStatus
        case _CDContextQueries.keyPathForDoNotDisturbStatus():
            return .doNotDisturbStatus
        case _CDContextQueries.keyPathForLowPowerModeStatus():
            return .lowPowerModeStatus
        case _CDContextQueries.keyPathForDeviceID():
            return .deviceID
        case _CDContextQueries.keyPathForDeviceName():
            return .deviceName
        case _CDContextQueries.keyPathForSiriActiveStatus():
            return .siriActiveStatus
        case _CDContextQueries.keyPathForCarConnectedStatus():
            return .carConnectedStatus
        case _CDContextQueries.keyPathForNavigationStatus():
            return .navigationStatus
        case _CDContextQueries.keyPathForMediaPlayingStatus():
            return .mediaPlayingStatus
        case _CDContextQueries.keyPathForKeybagLockStatus():
            return .keybagLockStatus
        case _CDContextQueries.keyPathForDeviceLockStatus():
            return .deviceLockStatus
        case _CDContextQueries.keyPathForFirstWakeupStatus():
            return .firstWakeupStatus
        case _CDContextQueries.keyPathForNextUserVisibleWakeDate():
            return .nextUserVisibleWakeDate
        case _CDContextQueries.keyPathForDeviceAssertionsHeldStatus():
            return .deviceAssertionsHeldStatus
        case _CDContextQueries.keyPathForDisplayOnBeforeFirstUnlockOfTheDayStatus():
            return .displayOnBeforeFirstUnlockOfTheDayStatus
        case _CDContextQueries.keyPathForBacklightOnStatus():
            return .backlightOnStatus
        case _CDContextQueries.keyPathForCallInProgressStatus():
            return .callInProgressStatus
        case _CDContextQueries.keyPathForForegroundApp():
            return .foregroundApp
        case _CDContextQueries.keyPathForLastUseDate():
            return .lastUseDate
        case _CDContextQueries.keyPathForInUseStatus():
            return .inUseStatus
        case _CDContextQueries.keyPathForHomeKitSceneDataDictionary():
            return .homeKitSceneDataDictionary
        case _CDContextQueries.keyPathForRecentMessages():
            return .recentMessages
        case _CDContextQueries.keyPathForRecentEmails():
            return .recentEmails
        case _CDContextQueries.keyPathForLocationCoordinates():
            return .locationCoordinates
        case _CDContextQueries.keyPathForAppUsageDataDictionaries():
            return .appUsageDataDictionaries
        case _CDContextQueries.keyPathForAppWebUsageDataDictionaries():
            return .appWebUsageDataDictionaries
        case _CDContextQueries.keyPathForBatteryStateDataDictionary():
            return .batteryStateDataDictionary
        case _CDContextQueries.keyPathForIntentsDataDictionary():
            return .intentsDataDictionary
        case _CDContextQueries.keyPathForCircularLocationRegions():
            return .circularLocationRegions
        case _CDContextQueries.keyPathForHomeKitAccessoryDataDictionary():
            return .homeKitAccessoryDataDictionary
        case _CDContextQueries.keyPathForAppDataDictionary():
            return .appDataDictionary
        case _CDContextQueries.keyPathForPredictedLocationOfInterestTransitions():
            return .predictedLocationOfInterestTransitions
        case _CDContextQueries.keyPathForActiveCall():
            return .activeCall
        case _CDContextQueries.keyPathForNowPlayingDataDictionary():
            return .nowPlayingDataDictionary
        case _CDContextQueries.keyPathForAudioOutputDataDictionary():
            return .audioOutputDataDictionary
        case _CDContextQueries.keyPathForDefaultPairedServicesAppearingForeground():
            return .defaultPairedServicesAppearingForeground
        case _CDContextQueries.keyPathForServicesAppearingForeground():
            return .servicesAppearingForeground
        case _CDContextQueries.keyPathForWorkoutDataDictionary():
            return .workoutDataDictionary
        case _CDContextQueries.keyPathForHomeKitAppViewDataDictionary():
            return .homeKitAppViewDataDictionary
        case _CDContextQueries.keyPathForSunriseSunsetDataDictionary():
            return .sunriseSunsetDataDictionary
        case _CDContextQueries.keyPathForBluetoothDataDictionary():
            return .bluetoothDataDictionary
        case _CDContextQueries.keyPathForUserActivityDataDictionary():
            return .userActivityDataDictionary
        case _CDContextQueries.keyPathForNFCTagIdentifiers():
            return .nFCTagIdentifiers
        case _CDContextQueries.keyPathForMDCSProxies():
            return .mDCSProxies
        case _CDContextQueries.keyPathForCurrentTimers():
            return .currentTimers
        case _CDContextQueries.keyPathForCurrentAlarms():
            return .currentAlarms
        case _CDContextQueries.keyPathForSiriServiceDataDictionary():
            return .siriServiceDataDictionary
        case _CDContextQueries.keyPathForDoNotDisturbStatusDataDictionary():
            return .doNotDisturbStatusDataDictionary
        default:
            assertionFailure("cannot translate to enum")
            return .activeCall
        }
    }
}
