#import <Foundation/Foundation.h>
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreDuet/_DKSyncCompositeOperation.h>

@class NSMutableArray;

@interface _DKSyncBlockCompositeOperation : _DKSyncCompositeOperation
{
    NSMutableArray *_blocks;
}

+ (id)blockCompositeOperationWithParent:(id)arg1 block:(id)arg2;
+ (id)blockCompositeOperationWithBlock:(id)arg1;

@property(readonly) NSMutableArray *blocks; // @synthesize blocks=_blocks;
- (void)main;
- (void)addExecutionBlock:(id)arg1;
- (id)executionBlocks;
- (id)initWithParent:(id)arg1 block:(id)arg2;
- (BOOL)isAsynchronous;
- (id)initWithBlock:(id)arg1;

@end

