#import <Foundation/Foundation.h>
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreDuet/_DKSyncOperation.h>

@class NSMutableArray;

@interface _DKSyncBlockOperation : _DKSyncOperation
{
    void* _lock;
    BOOL _asynchronous;
    NSMutableArray *_blocks;
}

+ (id)blockOperationWithBlock:(id)arg1;

@property(readonly) NSMutableArray *blocks; // @synthesize blocks=_blocks;
@property(getter=isAsynchronous) BOOL asynchronous; // @synthesize asynchronous=_asynchronous;
- (void)main;
- (void)addExecutionBlock:(id)arg1;
- (id)executionBlocks;
- (id)initWithBlock:(id)arg1;
- (id)init;

@end

